### PR TITLE
CC-12 # Add AWS Profile Management

### PR DESCRIPTION
**Pull request by simonmarklar**
- Replaced AWS SDK with @blinkmobile/aws-profile-management
- Added profile command to get and set the profile
- Updated documentation

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
I'd recommend bumping [blinkmobile/aws-profile-management](https://github.com/blinkmobile/aws-profile-management) to 1.0.0.

http://semver.org/#spec-item-9

> Numeric identifiers MUST NOT include leading zeroes.

I need to get used to this as well. I hadn't realised that they had formalised "1.0.0-alpha.2" and "1.0.0-beta.4".

**Comment by jokeyrhyme** [comment]
Just a question: is it at all possible to be able to infer the AWS profile from the scope? Could we recommend a profile naming convention that ensures this? I'm just wondering if it's possible to do away with separate `scope` and `profile` commands...

**Comment by simonmarklar** [comment]
re: semver -there's also http://semver.org/#spec-item-4  "Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable." so um er which one fits?! haha

I have no problems bumping the version number, but I guess that depends on if the public api is finalised. And that depends on this code review :) 

re: aws profile from scope
The profile is 'global' for all our cli's that use AWS as it represents a user in the clients account, but in this particular cli, scope is per project (each project goes in a separate bucket, bucket is scope), so I think it would get pretty messy if we infer it

**Comment by simonmarklar** [comment]
I expect @samblinkmobile will have some input on the client cli naming, but that shouldn't effect the api for aws-profile-management

**Comment by jokeyrhyme** [comment]
I'm satisfied that questions I have raised have been considered. Everything LGTM. 👍

**Pull request merged**
